name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checks out the repository's code
      - uses: gautamkrishnar/blog-post-workflow@master  # Uses the blog-post-workflow action
        with:
          max_post_count: "4"  # Maximum number of blog posts to fetch
          feed_list: "https://medium.com/feed/@akashvarunp"  # RSS feed URL of the Medium account
